package org.iso_relax.miaou.test;

/**
 * TestDataFactory is generated by Relaxer based on testData.rng.
 *
 * @version testData.rng 1.0 (Sat Sep 07 22:04:57 JST 2002)
 * @author  Relaxer 0.17b (http://www.relaxer.org)
 */
public class TestDataFactory {
    private static ITestDataFactory factory;

    /**
     * Sets a factory.
     *
     * @param newFactory
     */
    public static void setFactory(ITestDataFactory newFactory) {
        factory = newFactory;
    }

    /**
     * Gets the factory.
     *
     * @return ITestDataFactory
     */
    public static ITestDataFactory getFactory() {
        if (factory == null) {
            factory = new DefaultTestDataFactory();
        }
        return (factory);
    }
}
