package org.iso_relax.miaou.ss;

/**
 * SimpleSyntaxFactory is generated by Relaxer based on simpleSyntax.rng.
 *
 * @version simpleSyntax.rng 1.0 (Sat Sep 07 19:36:09 JST 2002)
 * @author  Relaxer 0.17b (http://www.relaxer.org)
 */
public class SimpleSyntaxFactory {
    private static ISimpleSyntaxFactory factory;

    /**
     * Sets a factory.
     *
     * @param newFactory
     */
    public static void setFactory(ISimpleSyntaxFactory newFactory) {
        factory = newFactory;
    }

    /**
     * Gets the factory.
     *
     * @return ISimpleSyntaxFactory
     */
    public static ISimpleSyntaxFactory getFactory() {
        if (factory == null) {
            factory = new DefaultSimpleSyntaxFactory();
        }
        return (factory);
    }
}
