package org.iso_relax.miaou.bta;

/**
 * BinaryTreeAutomatonFactory is generated by Relaxer based on binaryTreeAutomaton.rng.
 *
 * @version binaryTreeAutomaton.rng 1.0 (Sat Oct 19 02:26:43 JST 2002)
 * @author  Relaxer 0.17b (http://www.relaxer.org)
 */
public class BinaryTreeAutomatonFactory {
    private static IBinaryTreeAutomatonFactory factory;

    /**
     * Sets a factory.
     *
     * @param newFactory
     */
    public static void setFactory(IBinaryTreeAutomatonFactory newFactory) {
        factory = newFactory;
    }

    /**
     * Gets the factory.
     *
     * @return IBinaryTreeAutomatonFactory
     */
    public static IBinaryTreeAutomatonFactory getFactory() {
        if (factory == null) {
            factory = new DefaultBinaryTreeAutomatonFactory();
        }
        return (factory);
    }
}
